name: DiffuSETS
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20230802.0
  - absl-py=1.4.0
  - aiohttp=3.9.0
  - aiosignal=1.2.0
  - asttokens=2.4.1
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - cachetools=4.2.2
  - certifi=2024.8.30
  - cffi=1.16.0
  - chardet=4.0.0
  - click=8.1.7
  - comm=0.2.2
  - cryptography=41.0.7
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.22.0
  - google-auth-oauthlib=0.5.2
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - importlib_metadata=7.1.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.101
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=13.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.1
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.1.5
  - openssl=3.2.1
  - pandas=2.1.4
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - protobuf=3.20.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.4.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.5.1
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.6.0
  - threadpoolctl=3.5.0
  - tk=8.6.12
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - tornado=6.4
  - tqdm=4.65.0
  - traitlets=5.14.2
  - tzdata=2023c
  - werkzeug=2.2.3
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - annotated-types==0.6.0
      - anyio==4.3.0
      - bcrypt==4.1.1
      - blessed==1.20.0
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - crccheck==1.3.0
      - cycler==0.12.1
      - diffusers==0.27.2
      - distro==1.9.0
      - ecg-plot==0.2.8
      - einops==0.8.0
      - einsum==0.3.0
      - fonttools==4.46.0
      - fsspec==2023.12.2
      - gpustat==1.1.1
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.22.2
      - idna==3.6
      - imageio==2.35.1
      - importlib-metadata==7.0.0
      - ishneholterlib==2020.5.29
      - jiter==0.8.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - matplotlib==3.8.2
      - numba==0.60.0
      - nvidia-ml-py==12.535.133
      - openai==1.58.1
      - opt-einsum==3.4.0
      - packaging==23.2
      - paramiko==3.3.1
      - pillow==10.1.0
      - psutil==5.9.7
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - pynacl==1.5.0
      - pyparsing==3.1.1
      - pytorch-lightning==2.4.0
      - regex==2023.10.3
      - resampy==0.4.3
      - safetensors==0.4.1
      - scikit-image==0.24.0
      - scipy==1.11.4
      - seaborn==0.13.2
      - sniffio==1.3.1
      - soundfile==0.12.1
      - tifffile==2024.9.20
      - torchmetrics==1.4.2
      - typing-extensions==4.12.2
      - urllib3==2.1.0
      - wcwidth==0.2.12
      - wfdb==4.1.2
